### ISSUE TITLE
Nieaktywny przycisk Place Order

### ISSUE THREAD

**Issue by kadetth** [SnowdogApps/Hyva-Checkout-Inpost#1]
Po wybraniu opcji paczkomat, przycisk Place Order automatycznie się dezaktywuje. Po wybraniu paczkomatu staje się aktywny.
Jednak jeśli klient kliknie opcję paczkomatu a następnie wybierze na inną formę dostawy przycisk Place Ordrer wziąż pozostaje nieaktywny. Trzeba wybrać paczkomat, żeby móc skorzystać z innej formy dostawy.

**Comment by adamwaclawczyk** [comment]
@kadetth prośba o skorzystanie z wersji `1.3.0`
